### ISSUE TITLE
No results when raycasting to mock planes

### ISSUE THREAD

**Issue by dylandepass** [coder89/arfoundation-mock#2]
Thanks for this, support for mock is much needed in 2019. 

Trying to do a simple raycast against the mock planes in your sample but not getting back any results. Should that be working?

```
var screenCenter = Camera.main.ViewportToScreenPoint(new Vector3(0.5f, 0.5f));
var hits = new List<ARRaycastHit>();
raycastManager.Raycast(screenCenter, hits, UnityEngine.XR.ARSubsystems.TrackableType.All);

placementPoseIsValid = hits.Count > 0;
if (placementPoseIsValid)
{
   Debug.Log("Found");
}
```

Thanks Again

**Comment by lspas-volvo** [comment]
That's expected because raycast subsystem [XRRaycastSubsystem](https://docs.unity3d.com/ScriptReference/Experimental.XR.XRRaycastSubsystem.html) hasn't been implemented/mocked. One would need to implement mocked version of it to get ARRaycastManager to work.

**Comment by coder89** [comment]
That's expected because raycast subsystem XRRaycastSubsystem hasn't been implemented/mocked. One would need to implement mocked version of it to get ARRaycastManager to work.

Currently, I only had time to implement:
XRSessionSubsystem, XRPlaneSubsystem and XRReferencePointSubsystem.

To get complete solution we need XRDepthSubsystem (for point clouds) and XRRaycastSubsystem (for raycasting). I haven't implemented it since my project doesn't rely on any of that functionality.

I will probably have no time in the coming weeks to fix that so if there is anyone out there that would like to help out with that I am happy to provide some guidance and accept any contributions to this project. It should be fairly straightforward thing and should look similar to the existing subsystems that are already implemented.

**Comment by coder89** [comment]
Closing stale issue.
