### ISSUE TITLE
Unity 2019.2.8f1 not work raycast

### ISSUE THREAD

**Issue by Avatarchik** [coder89/arfoundation-mock#5]
It works, but at some point it stops working, I can’t understand why)

**Comment by coder89** [comment]
Take a look here:
https://github.com/coder89/arfoundation-mock/commit/70acf41b6ccf7b75f0d6eb4d1553f3e6fa6edfc2#diff-04e956ce0382b630f47d2e96d44dd036R161

This is not implemented. The point of this is just to mock raycast API so that you can initialize AR Foundation and call APIs but, as of today, it won't return anything meaningful. One would need to implement this method if you want to actually raycast and hit anything in your mocked scene.

**Comment by Avatarchik** [comment]
Hi! I noticed that if I remove the ARCore XR Plugin, then I work with raycast , but I do not work with the installed plugin
